"""run migrations for vaccination and trreatment tables

Revision ID: 8b56c1f4c4b0
Revises: 64d0ee55f7c8
Create Date: 2024-05-15 08:24:55.099677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b56c1f4c4b0'
down_revision = '64d0ee55f7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('cattle_serial_number', sa.Integer(), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.Column('drug_used', sa.String(length=100), nullable=True),
    sa.Column('method_of_administration', sa.String(length=100), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cattle_serial_number'], ['cattle.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination',
    sa.Column('vaccination_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.Column('cattle_serial_number', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('drug', sa.String(length=100), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cattle_serial_number'], ['cattle.serial_number'], ),
    sa.PrimaryKeyConstraint('vaccination_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination')
    op.drop_table('treatment')
    op.drop_table('worker')
    # ### end Alembic commands ###
